version: "3"

services: 
  trudesk-db:
    image: mongo:4.2
    ports: 
      - 27017:27017
    volumes: 
      - ./db-data:/data/db
  trudesk:
    build: .
    ports:
      - 80:8118
    depends_on: 
      - trudesk-db